apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-servicemonitor
  namespace: demo
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: http
    path: /

