apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    app: php
data:
  demo.conf: |-
    server {
      listen 0.0.0.0:8080;
      server_name _;
      root /app;

      location / {
        try_files $uri $uri/index.php;
      }

      location /metrics {
        try_files $uri /metrics.php;
      }
      
      location ~ \.php$ {
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }